spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: suhail
    password: suhail
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082


