spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5433/product
    username: suhail
    password: suhail
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
# connecting with eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# logging
logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

server:
  port: 8081